---
version: 2
jobs:
  build:
    docker:
      - image: library/docker:19-git
    working_directory: /tmp/build
    environment:
      DOCKER_IMAGE: balena/open-balena-api
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 19.03.8
      - run:
          name: Build
          command: |
            set -x

            echo "ENV COMMIT ${CIRCLE_SHA1}" >> Dockerfile

            docker pull "${DOCKER_IMAGE}:${CIRCLE_BRANCH}" || \
              docker pull "${DOCKER_IMAGE}:master" || true
            docker build --cache-from="${DOCKER_IMAGE}:${CIRCLE_BRANCH}" --cache-from="${DOCKER_IMAGE}:master" --rm=false --pull --tag "${DOCKER_IMAGE}:${CIRCLE_SHA1}" .

      - run:
          name: Install trivy
          command: |
            apk add --update-cache --upgrade curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Scan the local image with trivy
          command: trivy -f json -o report.json --no-progress --exit-code 0 --severity HIGH --ignore-unfixed ${DOCKER_IMAGE}:${CIRCLE_SHA1}

      - store_artifacts:
          path: /tmp/build/report.json

      - run:
          name: Test
          command: |
            set -ex

            IMAGE_NAME="${DOCKER_IMAGE}:${CIRCLE_SHA1}" ./automation/test.sh
